// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulCluster) DeepCopyInto(out *StatefulCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulCluster.
func (in *StatefulCluster) DeepCopy() *StatefulCluster {
	if in == nil {
		return nil
	}
	out := new(StatefulCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulClusterList) DeepCopyInto(out *StatefulClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StatefulCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulClusterList.
func (in *StatefulClusterList) DeepCopy() *StatefulClusterList {
	if in == nil {
		return nil
	}
	out := new(StatefulClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulClusterSpec) DeepCopyInto(out *StatefulClusterSpec) {
	*out = *in
	in.StatefulSetSpec.DeepCopyInto(&out.StatefulSetSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulClusterSpec.
func (in *StatefulClusterSpec) DeepCopy() *StatefulClusterSpec {
	if in == nil {
		return nil
	}
	out := new(StatefulClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulClusterStatus) DeepCopyInto(out *StatefulClusterStatus) {
	*out = *in
	in.StatefulSetStatus.DeepCopyInto(&out.StatefulSetStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulClusterStatus.
func (in *StatefulClusterStatus) DeepCopy() *StatefulClusterStatus {
	if in == nil {
		return nil
	}
	out := new(StatefulClusterStatus)
	in.DeepCopyInto(out)
	return out
}
